on:
  push:
    branches:
#      - master
#      - develop
      - feature/deploy-pkg
  pull_request:
    branches:
      - master
      - develop

name: R-CMD-build-check-deploy

jobs:
  R-CMD-build-check-deploy:
    runs-on: ${{ matrix.config.os }}

    name: ${{ matrix.config.os }} (${{ matrix.config.r }})

    strategy:
      fail-fast: false
      matrix:
        config:
#        - {os: windows-latest, r: 'release'}
#        - {os: macOS-latest, r: 'release'}
#        - {os: macOS-latest, r: 'devel'}
        - {os: ubuntu-16.04, r: 'release', rspm: "https://packagemanager.rstudio.com/cran/__linux__/xenial/latest"}

    env:
      R_REMOTES_NO_ERRORS_FROM_WARNINGS: true
      RSPM: ${{ matrix.config.rspm }}

    steps:
      - uses: actions/checkout@v2
      - uses: r-lib/actions/setup-r@master
        with:
          r-version: ${{ matrix.config.r }}
      - uses: r-lib/actions/setup-pandoc@master

      - name: Query dependencies
        run: |
          install.packages('remotes')
          saveRDS(remotes::dev_package_deps(dependencies = TRUE), ".github/depends.Rds", version = 2)
          writeLines(sprintf("R-%i.%i", getRversion()$major, getRversion()$minor), ".github/R-version")
        shell: Rscript {0}

      - name: Cache R packages
        if: runner.os != 'Windows'
        uses: actions/cache@v1
        with:
          path: ${{ env.R_LIBS_USER }}
          key: ${{ runner.os }}-${{ hashFiles('.github/R-version') }}-1-${{ hashFiles('.github/depends.Rds') }}
          restore-keys: ${{ runner.os }}-${{ hashFiles('.github/R-version') }}-1-

      - name: Install system dependencies
        if: runner.os == 'Linux'
        env:
          RHUB_PLATFORM: linux-x86_64-ubuntu-gcc
        run: |
          Rscript -e "remotes::install_github('r-hub/sysreqs')"
          sysreqs=$(Rscript -e "cat(sysreqs::sysreq_commands('DESCRIPTION'))")
          sudo -s eval "$sysreqs"

      - name: Install dependencies
        run: |
          remotes::install_deps(dependencies = TRUE)
          remotes::install_cran("rcmdcheck")
          remotes::install_cran("roxygen2")
          remotes::install_cran("drat") # need later to deploy
        shell: Rscript {0}

      - name: Roxygenize
        run: |
          roxygen2::roxygenize()
        shell: Rscript {0}

      - name: Build and Check
        env:
          _R_CHECK_CRAN_INCOMING_REMOTE_: false
        run: rcmdcheck::rcmdcheck(args = c("--no-manual", "--as-cran"), error_on = "warning",
            check_dir = "check")
        shell: Rscript {0}

      - name: Upload check results
        if: failure()
        uses: actions/upload-artifact@master
        with:
          name: ${{ runner.os }}-r${{ matrix.config.r }}-results
          path: check

# the following from https://stackoverflow.com/a/60548651/633251
      - name: Configure git
        env:
          TOKEN: ${{ secrets.HYSPC_EO_TOKEN }}
        run: git config --global url."https://${TOKEN}:x-oauth-basic@github.com/".insteadOf "https://github.com/"

      - name: Deploy -- clone
        if: success()
        run: |
          rm -rf archive
          git clone https://github.com/r-hyperspec/hySpc.pkgs.git archive
          #cd archive
          #git checkout master

      - name: Deploy -- insert
        if: success()
        run: |
          #setwd("../..")
          print(list.files(recursive = TRUE))
          #targz <- list.files(pattern = "\\.tar\\.gz")[1]
          #drat::insertPackage(targz, repodir = ".")
        shell: Rscript {0}

      - name: Deploy -- commit and push
        if: success()
        run: |
          #cd archive # move into the subdir, which is git controlled
          git add *
          git commit -m "Automated publish from hySpc.read.Witec"
          git push origin master
          rm -rf archive
