# on:
#   schedule:
#     - cron:  '*/1 * * * *'
#
# name: pub_to_hySpc_pkgs
#
# jobs:
#     - name: Move procedure
#       run: |
#         echo hi there
#         Rscript -e "dir.create('archive')"
#         git clone https://.:${{ secrets.GITHUB_TOKEN }}@github.com:r-hyperspec/hySpc.pkgs.git archive
#         cp .move_to_hySpc_pkgs.yml ./archive/hySpc.pkgs/src/contrib
#         git add hySpc.pkgs
#         git commit -m "Automatic publish from hySpc.read.Witec"
#         git push hySpc.pkgs master
# on:
#   schedule:
#     - cron:  '*/1 * * * *'
  # push:
  #   branches:
  #     - master
  #     - develop
  # pull_request:
  #   branches:
  #     - master
  #     - develop

# name: move-to-hySpc_pkgs
#
# jobs:
#   R-CMD-check:
#     runs-on: ${{ matrix.config.os }}
#
#     name: ${{ matrix.config.os }} (${{ matrix.config.r }})
#
#     strategy:
#       fail-fast: false
#       matrix:
#         config:
# #        - {os: windows-latest, r: 'release'}
# #        - {os: macOS-latest, r: 'release'}
# #        - {os: macOS-latest, r: 'devel'}
#         - {os: ubuntu-16.04, r: 'release', rspm: "https://packagemanager.rstudio.com/cran/__linux__/xenial/latest"}
#
#     env:
#       R_REMOTES_NO_ERRORS_FROM_WARNINGS: true
#       RSPM: ${{ matrix.config.rspm }}
#
#     steps:
#       - uses: actions/checkout@v2
#       - uses: r-lib/actions/setup-r@master
#         with:
#           r-version: ${{ matrix.config.r }}
#       - uses: r-lib/actions/setup-pandoc@master
#       - name: Query dependencies
#         run: |
#           install.packages('remotes')
#           dir.create("archive")
#         shell: Rscript {0}
name: Strategy-6
on: push

jobs:
  run:
    name: Strategy-6
    runs-on: ubuntu-latest
    steps:
    - name: Clone_hySpc.pkgs
      run: git clone https://.:${{ secrets.GITHUB_TOKEN }}@github.com:r-hyperspec/hySpc.pkgs.git

    - name: Move_into_dir
      run: cd hySpc.pkgs

    - name: Checkout_repo
      uses: actions/checkout@v2

    - name: Create_file
      run: echo je ne perdrai pas > test.txt

    - name: Commit_changes
      uses: EndBug/add-and-commit@v4
      with:
        author_name: eoduniyi
        author_email: eeoduniyi@gmail.com
        message: "Cloned hySpc.pkgs and move test file into it"
      env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}