# on:
#   schedule:
#     - cron:  '*/1 * * * *'
#
# name: pub_to_hySpc_pkgs
#
# jobs:
#     - name: Move procedure
#       run: |
#         echo hi there
#         Rscript -e "dir.create('archive')"
#         git clone https://.:${{ secrets.GITHUB_TOKEN }}@github.com:r-hyperspec/hySpc.pkgs.git archive
#         cp .move_to_hySpc_pkgs.yml ./archive/hySpc.pkgs/src/contrib
#         git add hySpc.pkgs
#         git commit -m "Automatic publish from hySpc.read.Witec"
#         git push hySpc.pkgs master
on:
  schedule:
    - cron:  '*/1 * * * *'
  # push:
  #   branches:
  #     - master
  #     - develop
  # pull_request:
  #   branches:
  #     - master
  #     - develop

name: move-to-hySpc_pkgs

jobs:
  R-CMD-check:
    runs-on: ${{ matrix.config.os }}

    name: ${{ matrix.config.os }} (${{ matrix.config.r }})

    strategy:
      fail-fast: false
      matrix:
        config:
#        - {os: windows-latest, r: 'release'}
#        - {os: macOS-latest, r: 'release'}
#        - {os: macOS-latest, r: 'devel'}
        - {os: ubuntu-16.04, r: 'release', rspm: "https://packagemanager.rstudio.com/cran/__linux__/xenial/latest"}
