name: pub_to_hySpc_pkgs
on: push

jobs:
  run:
    name: pub_to_hySpc_pkgs
    runs-on: ubuntu-latest
    steps:

    - name: Clone_Move_Checkout_Add_&_Commit
      run: |
        git clone https://github.com/r-hyperspec/hySpc.pkgs.git
        mkdir archive
        mv hySpc.pkgs archive
        cd archive/hySpc.pkgs
        echo I want to thank God, my family/siblings, the r-hyperspec team, big brother Google, all my mentors, my K-12 teachers for putting up with me, and the U.S education system for helping me understand that while K-12 + higher ed is intellectually priceless is mostly a scam. > test.txt
        mv test.txt src/contrib
        cd src/contrib
        git config --global user.email "eeoduniyi@gmail.com"
        git config --global user.name "eoduniyi"
        git add -A
        git commit -m "Automatic publish from hySpc.read.Witec"
      env:
        REPO_KEY: ${{ secrets.HYSPC_EO_TOKEN }}
        USERNAME: r-hyperspec
    - name: Push
      uses: ad-m/github-push-action@master
      with:
        repository: 'r-hyperspec/hySpc.pkgs'
        directory: './archive/hySpc.pkgs'
        github_token: ${{ secrets.HYSPC_EO_TOKEN }}
